baseURL = "https://mijndertstuij.nl"
languageCode = "en-us"
title = "Mijndert Stuij"
theme = "rocinante"
paginate = 10

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[Author]
  name = "Mijndert Stuij"
  email = "mijndert@mijndertstuij.nl"

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["posts"]
  email = "mijndertstuij.nl"
  about = """
I'm an AWS solutions architect with over 14 years of experience building highly scalable, high performance infrastructure. My passion is scaling out infrastructure from 0 to millions of users while adhering to industry best-practices in a cost-effective manner.

🤓
"""

[[params.links]]
  [[params.links.link]]
      name = "Uses"
      href = "/uses"
      new_tab = false
    [[params.links.link]]
      name = "Now"
      href = "/now"
      new_tab = false
    [[params.links.link]]
      name = "Mastodon"
      href = "https://toot.community/@mijndert"
      new_tab = true
    [[params.links.link]]
      name = "GitHub"
      href = "https://github.com/mijndert"
      new_tab = true
    [[params.links.link]]
      name = "RSS"
      href = "https://mijndertstuij.nl/posts/index.xml"
      new_tab = true